background { 
    monitor =
#    path = screenshot
    path = ~/Pictures/botw/168.jpg
    color = rgb(30, 30, 46)
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 150, 30
    outline_thickness = 0
    inner_color = rgba(255, 255, 255, 0.2)

	placeholder_text = <span foreground='##ffffffdd'><i>Password</i></span>
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 12

    position = 0, -100
    halign = center
    valign = center
}

#Time
label {		
	monitor = 
	text = cmd[update:1000] echo "<span weight='900'>$TIME12</span>"
	color = rgb(255, 255, 255)
	font_size = 68
	font_family = Red Hat Display
	
	position = 0, 100
	halign = center
	valign = center
}

#Date
label {		
	monitor = 
	text = cmd[update:1000] echo "<span weight='600'>$(date "+%A, %B %d, %Y")</span>"
	color = rgb(255, 255, 255)
	font_size = 14
	font_family = Red Hat Display
	
	position = 0, 50
	halign = center
	valign = center
}
