##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
	name = blueman-manager
	match:class = blueman-manager

	float = on
	pin = on
	stay_focused = on
}

windowrule {
	name = pavucontrol
	match:class = org.pulseaudio.pavucontrol

	float = on
	pin = on
	stay_focused = on
}

windowrule {
	name = vicinae
	match:class = vicinae
	
	float = on
	pin = on
	stay_focused = on
}

windowrule = opacity 0.9,match:class com.github.th_ch.youtube_music
windowrule = opacity 0.9,match:class thunar
windowrule = opacity 0.9,match:class vesktop

layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = blur on, match:namespace swayosd
layerrule = blur on, match:namespace rofi

layerrule = ignore_alpha 0, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace rofi

layerrule = ignore_alpha 0.5, match:namespace waybar
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.49, match:namespace swayosd
layerrule = ignore_alpha 0.5, match:namespace rofi
