##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
	name = float-center-focused
	match:class = blueman-manager|vicinae|org.kde.kdeconnect.handler|gay.vaskel.soteria

	float = on
	stay_focused = on
	center = on
}

windowrule {
	name = pavucontrol
	match:class = org.pulseaudio.pavucontrol

	float = on
	stay_focused = on
	center = on
	size = (window_w*1.45) (window_h*1.3)
}


windowrule {
	name = thunar-rename-float
	match:class = thunar
	match:title = Rename(.*)|File Operation Progress
	
	float = on
	stay_focused = on
}



windowrule {
	name = transclusent
	match:class = thunar|vesktop|com.github.th_ch.youtube_music|io.github.elyprismlauncher.ElyPrismLauncher
	
	opacity = 0.9
}

windowrule {
	name = about-float
	match:class = kitty
	match:tag = about

	float = on
	center = on
	size = 1600 900
}

windowrule {
	name = update-float
	match:class = kitty
	match:tag = update

	float = on
	center = on
	size = 1600 900
}


layerrule {
	name = blur_layers
	match:namespace = waybar|swaync-control-center|swaync-notification-window|swayosd|rofi|vicinae

	blur = on
	blur_popups = on
	ignore_alpha = 0.49
}
