##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule = float,stayfocused,pin,class:blueman-manager
windowrule = float,stayfocused,pin,class:org.pulseaudio.pavucontrol
windowrule = opacity 0.9,class:com.github.th_ch.youtube_music
windowrule = opacity 0.9,class:thunar
windowrule = opacity 0.9,class:vesktop
windowrule = stayfocused,pin,class:vicinae

layerrule = blur,waybar
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = blur, swayosd
layerrule = blur, vicinae

layerrule = ignorezero, waybar
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorezero, vicinae

layerrule = ignorealpha 0.5, waybar
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window
layerrule = ignorealpha 0.49, swayosd
