# Cursor
cursor 					#e6e0e9
cursor_text_color		#141218

# Text
foreground 				#e6e0e9
background				#141218

# Selection
selection_foregorund	#36275d
selection_background	#cfbdfe

# URL
url_color				#cfbdfe

# ANSI Colors
# Black
color0					#2b292f
color8					#2b292f

# Red
color1					#ffb4ab
color9					#ffb4ab

# Green
color2					#cabde0
color10					#cabde0

# Yellow
color3					#efb8c8
color11					#efb8c8

# Blue
color4					#cfbdfe
color12					#cfbdfe

# Magenta
color5					#e68ea8
color13					#e68ea8

# Cyan
color6					#b497fd
color14					#b497fd

# White
color7					#e6e0e9
color15					#e6e0e9

# Tab Bar
active_tab_foreground	#e9ddff
active_tab_background	#4d3d75
inactive_tab_foreground	#cac4cf
inactive_tab_background	#211f24

# Border
active_border_color		#cfbdfe

# Bell
visual_bell_color		#0f0d13
