include catppuccin-mocha.conf

font_family family="CaskaydiaCove Nerd Font"

font_size 11.7

disable_ligatures always

background_opacity 0.9

cursor_shape beam

confirm_os_window_close 0

visual_bell_duration 0.65
visual_bell_color #181825
enable_audio_bell no

map ctrl+shift+left
map ctrl+shift+right
